language: java
jdk:
  - openjdk7
  - oraclejdk8
before_install:
    - cp ./etc/settings.xml ~/.m2/
    - cp ./etc/settings-arquillian.xml ~/
    - cp ./etc/onFailure.sh  ~/
    - cp ./etc/logging.properties  ~/
    - chmod 777 ~/onFailure.sh
    - git submodule update --init --recursive
    - git submodule foreach git pull origin master
script:
    - mvn -B clean verify cobertura:cobertura coveralls:cobertura -Dorg.apache.maven.user-settings=~/settings-arquillian.xml -Dorg.apache.maven.global-settings=~/settings-arquillian.xml
after_failure: ~/onFailure.sh
notifications:
  email: false
  irc:
    channels:
            - chat.freenode.net#lightblue
    on_success: always

